const TEMPLATE_KEY = 'joining-portal:email-templates:v3'
const DATES_KEY = 'joining-portal:key-dates:v1'

const AUTOMATED_EMAIL_IDS = new Set(['parent_verification', 'booking_nudge', 'open_night_reminder', 'open_night_final_reminder', 'paperwork_reminder', 'code_expiry_warning', 'start_reminder_7_days', 'start_reminder_24_hours'])

export function emailPortalUrl(templateId, { appUrl, familyId = '', accessToken = '' }) {
  const base = String(appUrl || '').replace(/\/$/, '')
  if (['joining_code', 'paperwork_reminder', 'code_expiry_warning'].includes(templateId)) return `${base}/#/join`
  if (templateId === 'missed_intake_staff_alert') return `${base}/#/staff`
  if (templateId === 'withdrawal_confirmation') return `${base}/#/`
  return `${base}/#/family/${familyId}/${accessToken}`
}

export const DEFAULT_EMAIL_TEMPLATES = [
  { id: 'family_return_link', name: 'Return-to-enquiry link', trigger: 'Immediately when a registered parent asks to return to an existing enquiry', recipient: 'Parent or guardian', active: true, subject: 'Return to your 1330 Squadron joining enquiry', body: 'Dear {{parentName}},\n\nUse the secure link below to return to your family joining record:\n\n{{portalUrl}}\n\nIf you did not request this link, you can ignore this email.' },
  { id: 'open_night_date_changed', name: 'Open Night date changed', trigger: 'Immediately when staff change a date containing existing bookings', recipient: 'Affected parents or guardians', active: true, subject: 'Important: Open Night date changed for {{cadetName}}', body: 'Dear {{parentName}},\n\nThe Open Night booked for {{cadetName}} has moved from {{oldDate}} to {{newDate}}.\n\nYour booking has been moved automatically. If the new date is unsuitable, return to the portal to choose another date or withdraw.\n\nReview your booking: {{portalUrl}}' },
  { id: 'parent_verification', name: 'Parent verification', trigger: 'Immediately after an enquiry is submitted or parent details are updated', recipient: 'Parent or guardian', active: false, subject: 'Confirm your 1330 Squadron enquiry', body: 'Please use the verification code below to confirm that the contact details supplied for {{cadetName}} are correct and that you are happy for the Squadron to contact you about recruitment.' },
  { id: 'booking_nudge', name: 'Open Night booking nudge', trigger: '48 hours after parent verification if no Open Night has been booked', recipient: 'Parent or guardian', active: false, subject: 'Please book {{cadetName}}’s 1330 Squadron Open Night', body: 'Dear {{parentName}},\n\nThank you for confirming your interest in 1330 Squadron. The next step is to book an Open Night for you and {{cadetName}} to attend together.\n\nWe cannot progress the enquiry until you have attended an Open Night. Please return to the joining portal and choose a suitable date.' },
  { id: 'open_night_confirmation', name: 'Open Night confirmation', trigger: 'Immediately after an Open Night is booked or rebooked', recipient: 'Parent or guardian', active: true, subject: 'Open Night confirmed for {{cadetName}} - {{openNightDate}}', body: 'Dear {{parentName}},\n\nThis confirms the Open Night place for {{cadetName}} on {{openNightDate}}.\n\nPlease arrive at 7.10pm and wait at the gate at Peninsula Barracks, O’Leary Street, Warrington, WA2 7QS. The gate will open at 7.15pm. A parent or guardian and the prospective cadet must attend together. Both parents or guardians are very welcome to attend.\n\nThis is a formal introduction to a uniformed youth organisation based on the values and standards of the Royal Air Force. Prospective cadets should dress smartly. Hair should be neat and make-up, if worn, should be suitable for the occasion. Prospective cadets should address uniformed staff as Sir or Ma’am unless asked to use another form of address.\n\nThe evening begins with a presentation about the Squadron and what cadets and parents can expect. The Officer Commanding will give a short welcome brief. Squadron cadets will lead a tour, followed by a demonstration from one of our teams. At the end, staff will issue the code needed to access the joining paperwork and confirm the proposed start date.\n\nIf you cannot attend, you must rebook through the portal as early as possible. Staff and cadets plan the evening around confirmed attendance.' },
  { id: 'open_night_reminder', name: 'Open Night reminder', trigger: '7 days before the booked Open Night', recipient: 'Parent or guardian', active: false, subject: 'One week to {{cadetName}}’s 1330 Squadron Open Night', body: 'Dear {{parentName}},\n\nThis is a reminder that {{cadetName}} is booked to attend the 1330 Squadron Open Night on {{openNightDate}}. Please arrive together at 7.10pm and wait at the gate at Peninsula Barracks, O’Leary Street, Warrington, WA2 7QS.\n\nProspective cadets must dress smartly, with neat hair and make-up suitable for the occasion. They should address uniformed staff as Sir or Ma’am unless corrected otherwise.\n\nThe evening runs until approximately 8.30pm. If you can no longer attend, please return to the portal now and rebook. Please do not simply miss the evening.' },
  { id: 'open_night_final_reminder', name: 'Final Open Night reminder', trigger: '24 hours before the booked Open Night', recipient: 'Parent or guardian', active: false, subject: 'Tomorrow: Open Night for {{cadetName}} at 1330 Squadron', body: 'Dear {{parentName}},\n\nWe look forward to welcoming you and {{cadetName}} tomorrow. Please arrive at 7.10pm and wait at the gate at Peninsula Barracks, O’Leary Street, Warrington, WA2 7QS. The gate opens at 7.15pm.\n\nPlease remember that both the prospective cadet and a parent or guardian must attend. Prospective cadets should be smartly dressed and should address uniformed staff as Sir or Ma’am.\n\nIf an unavoidable problem means you cannot attend, use the portal to rebook before the event.' },
  { id: 'joining_code', name: 'Thank you and joining code', trigger: 'Immediately when staff approve Open Night attendance', recipient: 'Parent or guardian', active: true, subject: 'Thank you for attending - joining paperwork for {{cadetName}}', body: 'Dear {{parentName}},\n\nThank you for attending our Open Night with {{cadetName}}. We hope you found the presentation and tour useful. We are pleased that they would like to continue and look forward to welcoming them to the Squadron.\n\nTheir joining code is {{joiningCode}}. It expires on {{codeExpiry}}.\n\nPlease return to the joining portal and complete all of the formal paperwork, joining fee, Direct Debit and Gift Aid steps. We cannot accept {{cadetName}} onto the intake until this has been completed. Once the code has been accepted, it will not be requested again.' },
  { id: "direct_joining_link", name: "Direct joiner paperwork link", trigger: "When staff add a direct joiner who is not attending an Open Night", recipient: "Parent or guardian", active: true, subject: "Joining paperwork for {{cadetName}}", body: "Dear {{parentName}},\n\nThank you for enquiring about 1330 Squadron.\n\nEverything is ready for {{cadetName}} to join. The button below opens the joining paperwork, where you will complete the Form 3822, pay the joining fee and set up the monthly subscription.\n\nPlease work through it in one sitting, as progress is not saved if you close the page. Please keep this link to yourself: it opens your family record and does not need a code." },
  { id: 'paperwork_reminder', name: 'Joining paperwork reminder', trigger: '7 days after Open Night attendance if the paperwork is not complete', recipient: 'Parent or guardian', active: false, subject: 'Joining paperwork still required for {{cadetName}}', body: 'Dear {{parentName}},\n\nWe are looking forward to welcoming {{cadetName}} to 1330 Squadron, but their joining paperwork has not yet been completed.\n\nPlease return to the joining portal and complete the Form 3822, joining fee, Direct Debit, Gift Aid and final confirmation steps. We cannot accept them onto the intake until everything is complete. Their joining code expires on {{codeExpiry}}.' },
  { id: 'code_expiry_warning', name: 'Final joining-code expiry warning', trigger: '72 hours before an unused joining code expires', recipient: 'Parent or guardian', active: false, subject: 'Urgent: {{cadetName}}’s joining code expires soon', body: 'Dear {{parentName}},\n\nThe joining code issued for {{cadetName}} expires on {{codeExpiry}} and the paperwork has not been started.\n\nPlease return to the joining portal and begin the application before the deadline. If the code expires unused, you and {{cadetName}} will need to attend another Open Night before the application can continue.' },
  { id: 'nonattendance', name: 'Step 6 alternative - did not attend, return to booking', trigger: 'When staff select Did not attend instead of approving attendance', recipient: 'Parent or guardian', active: true, subject: 'Action required following {{cadetName}}’s missed Open Night', body: 'Dear {{parentName}},\n\n{{cadetName}} was booked to attend a 1330 Squadron Open Night on {{openNightDate}}, but the booking was not moved and you did not attend.\n\nOur staff and cadets give up a full parade night to prepare the presentation, tour and demonstrations for booked families. Confirmed places must therefore be treated as a commitment. If circumstances change, we expect families to tell us in advance so that the place can be released.\n\nPlease return to the joining portal and either book another Open Night or withdraw the enquiry. A new booking returns the application to step 2. We cannot issue a joining code or progress the application until you attend an Open Night with {{cadetName}}.' },
  { id: 'withdrawal_confirmation', name: 'Application withdrawn', trigger: 'Immediately before a parent or staff member withdraws and removes an application', recipient: 'Parent or guardian', active: true, subject: 'Application withdrawn for {{cadetName}}', body: 'Dear {{parentName}},\n\nThis confirms that the application for {{cadetName}} has been withdrawn from the 1330 Squadron recruitment process.\n\nYou will not receive any further recruitment emails about this application. If it was withdrawn in error, please contact the Squadron as soon as possible.\n\nIf {{cadetName}} would like to join in the future, you are welcome to register a new interest through the joining portal. The application will begin again from the first step and you will need to book another Open Night.' },
  { id: 'joining_complete', name: 'Joining completed - parent confirmation', trigger: 'When Form 3822, payments, Gift Aid and final confirmations are completed', recipient: 'Parent or guardian; staff receive the existing Bader submission separately', active: true, subject: 'All set for {{cadetName}} to join 1330 Squadron', body: 'Dear {{parentName}},\n\nEverything is now complete and {{cadetName}} is registered to start with 1330 (Warrington) Squadron on {{startDate}} at 6.30pm.\n\nFor the first night, they should arrive in school uniform and bring a full water bottle, a notepad and pen.\n\nPlease keep an eye on the 1330 Parents and Guardians Signal group for parade-night changes, event information and important Squadron updates. Parent group: https://signal.group/#CjQKIJl8L_m4RIX-eXFqO_wg0W67AFFtSTaSblV85N69sJpuEhA3cQq0MDddoeUX1NK03zwp\n\nYour cadet should also join the Cadet Signal group and register as Cdt Firstname Surname. Cadet group: https://signal.group/#CjQKIH7uvVYV4_6nkB2_On2y7TGMKyavN9l0x-7fIA2Hu643EhAHIDTmsmZJ_9tAC9_b8Jrt\n\nBoth groups should have phone-number visibility set to private. If either request has not yet been completed, please do it now.\n\nWe look forward to seeing {{cadetName}} on parade.' },
  { id: 'start_reminder_7_days', name: 'Start-date reminder - 7 days', trigger: '7 days before the confirmed start date, if there is sufficient time', recipient: 'Parent or guardian', active: false, subject: 'One week until {{cadetName}} starts at 1330 Squadron', body: 'Dear {{parentName}},\n\n{{cadetName}} is due to start at 1330 Squadron in one week, on {{startDate}} at 6.30pm.\n\nThey should arrive in school uniform and bring a full water bottle, a notepad and pen. Please check the Parents and Guardians Signal group during the week in case there are any parade-night updates.' },
  { id: 'start_reminder_24_hours', name: 'Final start-date reminder - 24 hours', trigger: '24 hours before the confirmed start date', recipient: 'Parent or guardian', active: false, subject: 'Tomorrow: {{cadetName}} starts at 1330 Squadron', body: 'Dear {{parentName}},\n\nWe look forward to welcoming {{cadetName}} to 1330 Squadron tomorrow at 6.30pm.\n\nThey should arrive in school uniform with a full water bottle, a notepad and pen. Please check the Signal group before travelling for any last-minute update.' },
  { id: 'missed_intake_staff_alert', name: 'Missed intake staff alert', trigger: 'When an active application remains outstanding 14 days after the intended start date', recipient: 'Squadron Ops', active: true, subject: 'Action required: applications have missed their intended start date', body: 'Dear Squadron Staff,\n\nThe following prospective cadets are still active more than 14 days after their intended start date:\n\n{{outstandingList}}\n\nPlease review each application and check whether the family has been in contact. If they are no longer joining, withdraw and remove the application from the staff dashboard.' },
].map((template) => AUTOMATED_EMAIL_IDS.has(template.id) ? { ...template, active: true } : template)

export const DEFAULT_KEY_DATES = {
  openNights: ['2026-09-17', '2026-09-24', '2026-11-19', '2027-01-14', '2027-03-18', '2027-03-25'],
  intakeDates: ['04-01', '10-01'],
  openNightStart: '19:15', arrivalTime: '19:10', openNightEnd: '20:30',
  paradeDays: 'Monday and Thursday', paradeTime: '18:30', joiningCodeDays: 30,
  monthlyEmailDay: 1, reminderDaysBefore: 7, finalReminderHoursBefore: 24,
}

export function getEmailTemplates() { try { return JSON.parse(localStorage.getItem(TEMPLATE_KEY)) || DEFAULT_EMAIL_TEMPLATES } catch { return DEFAULT_EMAIL_TEMPLATES } }
export function saveEmailTemplates(value) { localStorage.setItem(TEMPLATE_KEY, JSON.stringify(value)); saveSharedSetting('emailTemplates', value).catch((error) => console.error('Could not sync email templates:', error)) }
export function getKeyDates() { try { return { ...DEFAULT_KEY_DATES, ...(JSON.parse(localStorage.getItem(DATES_KEY)) || {}) } } catch { return DEFAULT_KEY_DATES } }
export function saveKeyDates(value) { localStorage.setItem(DATES_KEY, JSON.stringify(value)); saveSharedSetting('keyDates', value).catch((error) => console.error('Could not sync key dates:', error)) }

export function hydrateCommunicationSettings(settings = {}) {
  if (settings.emailTemplates) localStorage.setItem(TEMPLATE_KEY, JSON.stringify(settings.emailTemplates))
  if (settings.keyDates) localStorage.setItem(DATES_KEY, JSON.stringify(settings.keyDates))
}
import { saveSharedSetting } from './sharedRecruitmentStore.js'
